log_level = "info"
device_name = "Microsoft X-Box 360 pad"
# device2_name = "@None"
outputter = "terminal"
history_size = 30
# inputlog_path = "@None"
write_default_config = true
[outputters.terminal]

[outputters.browser]
port = 8000
host = "0.0.0.0"

[outputters.gui]
font_path = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
font_size = 32
width = 300
height = 1200